### ISSUE TITLE
the ideology with "An infinite, parallel (multiprocess) batch generator" in NCEData?

### ISSUE THREAD

**Issue by worthless443** [inejc/paragraph-vectors#32]
Hi there!

I kind of don't seem to understand the idealogy behind the class `NCEData` in `data.py`. The description seems to tell "An infinite, parallel (multiprocess) batch generator fo rnoise-contrastive estimation of word vector models". Can I have some more resources on it and some tips on using/implementing it?

Thanks :)

**Comment by inejc** [comment]
Hey, the generator produces batches of training data on multiple cores (using `multiprocessing`). It is infinite in a sense that you can query it forever (it loops over all dataset and when it reaches the end starts again). You can find and example on how to initialize and start it [here](https://github.com/inejc/paragraph-vectors/blob/33f6465208f738a5dac69810d709459cc99ed704/paragraphvec/train.py#L96).

You then need to call `data_generator = nce_data.get_generator()` in order to obtain the actual data generator which then produces the batches like this:
```python
batch = next(data_generator)
batch = next(data_generator)
batch = next(data_generator)
...
```

Does this answer your question?
